// Generated from actual frozen OpenAPI. Do not edit by hand.
// api-v1.ts remains the canonical domain/display contract; this file covers HTTP DTOs.
export type APIError = { "error": ErrorPayload; };
export type AuthResponse = { "user": User; };
export type ClientRenderMetrics = { "client_id": string; "latency_upper": DurationStats; "receive_to_render": DurationStats; "invalid_samples": number; "hidden_samples": number; "unreported_events": number; "latency_exceedances": number; };
export type ClockProbe = { "server_received_ms": number; "server_sent_ms": number; };
export type CommandEnvelope = { "request_id": string; "run_id": string; "expected_input_revision": number; };
export type CommandReceiptResponse = { "request_id": string; "run_id": string; "input_revision": number; "state_version": number; "result": { [key: string]: unknown; }; };
export type Config = { "config_version": number; "weights": { [key: string]: number; }; "category_thresholds": { [key: string]: number; }; "planner": { [key: string]: number; }; "units": { [key: string]: string; }; };
export type ConfigPatch = { "weights"?: (ConfigWeights | null); "category_thresholds"?: (ConfigThresholds | null); "planner"?: (PlannerLimits | null); };
export type ConfigPatchInput = { "request_id": string; "run_id": string; "expected_input_revision": number; "patch": ConfigPatch; };
export type ConfigThresholds = { "normal_min": number; "attention_min": number; };
export type ConfigWeights = { "throughput": number; "delay": number; "occupancy": number; "conflicts": number; "resource_idle": number; };
export type Conflict = { "id": string; "kind": "route_overlap" | "track_occupied" | "resource_unavailable" | "precedence" | "capacity" | "destination_closed"; "severity": "warning" | "critical"; "reason_code": string; "entity_ids": Array<string>; "operation_ids": Array<string>; "message": string; "recommendation": string; "detected_at": string; };
export type DepartureExplanation = { "train_id": string; "departure_sim_s": (number | null); "delay_sim_s": (number | null); "basis": "actual" | "forecast"; };
export type DurationStats = { "sample_count": number; "p50_ms": (number | null); "p95_ms": (number | null); "max_ms": (number | null); };
export type Edge = { "id": string; "from_node_id": string; "to_node_id": string; "track_id": (string | null); "zone_id": (string | null); "bidirectional": boolean; };
export type Efficiency = { "mode": "actual" | "forecast"; "formula_version": string; "window_start_sim_s": number; "window_end_sim_s": number; "score": (number | null); "category": ("normal" | "attention" | "critical" | null); "factors": Array<Factor>; };
export type ErrorPayload = { "code": string; "message": string; "details": { [key: string]: unknown; }; "request_id": (string | null); };
export type ExplainedPlan = { "plan_id": string; "changes": Array<OperationDiff>; "departures": Array<DepartureExplanation>; "reason": string; };
export type ExplanationAvailable = { "available": true; "run_id": string; "replan_id": string; "base_event_seq": number; "base_plan_id": (string | null); "plans": Array<ExplainedPlan>; };
export type ExplanationUnavailable = { "available": false; "reason": string; "plans": Array<ExplainedPlan>; };
export type Factor = { "key": "throughput" | "delay" | "occupancy" | "conflicts" | "resource_idle"; "raw": (number | null); "unit": string; "norm_penalty": (number | null); "weight": number; "contribution": (number | null); "reason": string; };
export type HealthLive = { "status": "alive"; "stage": string; };
export type HealthReady = { "status": "ready"; "stage": string; "checks": { [key: string]: string; }; "capabilities": { [key: string]: boolean; }; };
export type HistoryEvent = { "run_id": string; "seq": number; "server_time": string; "sim_time_s": number; "kind": string; "entity_ids": Array<string>; "message": string; "actor_user_id": (string | null); };
export type HistoryPage = { "items": Array<HistoryEvent>; "next_from_seq": number; "has_more": boolean; "anchor_seq": number; "available_from_wall_time": string; "available_to_wall_time": string; };
export type Incident = { "id": string; "kind": "train_delay" | "track_closure" | "resource_loss" | "destination_block"; "target_id": string; "status": "active" | "pending" | "resolved"; "created_at": string; "starts_sim_s": number; "ends_sim_s": number; "delay_sim_s": (number | null); "affected_operation_ids": Array<string>; "description": string; };
export type IncidentBatchInput = { "request_id": string; "run_id": string; "expected_input_revision": number; "items": Array<IncidentInput>; };
export type IncidentInput = { "kind": "train_delay" | "track_closure" | "resource_loss" | "destination_block"; "target_id": string; "duration_sim_s": number; "delay_sim_s"?: (number | null); };
export type Layout = { "view_box": [number, number, number, number]; "nodes": Array<Node>; "edges": Array<Edge>; "tracks": Array<TrackGeometry>; "routes": Array<RouteGeometry>; };
export type LoginInput = { "username": string; "password": string; };
export type MetricsResponse = { "run_id": string; "window_started_at": string; "measured_at": string; "published_events": number; "connected_clients": number; "actor_queue_depth": number; "planner_running_jobs": number; "planner_pending_jobs": number; "ui_render": Array<ClientRenderMetrics>; "replans": ReplanMetrics; };
export type NewRunInput = { "request_id": string; "run_id": string; "expected_input_revision": number; "scenario_id": string; "seed": number; };
export type Node = { "id": string; "kind": "boundary" | "switch_zone" | "track_end"; "x": number; "y": number; "switch_ids": Array<string>; };
export type Operation = { "id": string; "train_id": string; "group_ids": Array<string>; "kind": "arrival" | "inspection" | "shunt_transfer" | "cargo" | "departure_prep" | "departure"; "status": "pending" | "planned" | "running" | "completed" | "blocked"; "execution_mode": "auto" | "manual"; "predecessor_ids": Array<string>; "source_track_id": (string | null); "target_track_id": (string | null); "route_ids": Array<string>; "resource_ids": Array<string>; "duration_sim_s": number; "start_sim_s": (number | null); "end_sim_s": (number | null); "actual_start_sim_s": (number | null); "actual_end_sim_s": (number | null); "progress": number; "phase": ("empty_to_source" | "couple" | "pull_to_lead" | "reverse" | "push_to_target" | "uncouple" | "return_to_depot" | null); "blocked_reason_codes": Array<string>; "assigned_user_id": (string | null); "can_complete": boolean; };
export type OperationDiff = { "operation_id": string; "train_id": string; "label": string; "before_start_sim_s": (number | null); "after_start_sim_s": (number | null); "shift_sim_s": (number | null); "before_track_id": (string | null); "after_track_id": (string | null); "before_resource_ids": Array<string>; "after_resource_ids": Array<string>; };
export type Park = { "id": string; "name": string; "kind": "receiving_departure" | "sorting" | "cargo" | "service"; };
export type PhysicalLocation = { "kind": "boundary" | "track" | "route" | "departed"; "boundary_id"?: (string | null); "track_id"?: (string | null); "route_id"?: (string | null); "operation_id"?: (string | null); "route_progress"?: (number | null); };
export type PlanDetail = { "id": string; "status": "proposed" | "active" | "superseded" | "stale" | "rejected"; "validity": "feasible" | "invalid"; "optimization_run_id": string; "strategy": string; "base_input_revision": number; "base_state_version": number; "base_active_plan_id": (string | null); "config_version": number; "created_at": string; "cutover_sim_s": number; "forecast": Efficiency; "objective_value": (number | null); "changed_operation_ids": Array<string>; "explanation": Array<string>; "can_apply": boolean; "operations": Array<Operation>; "validator": ValidatorReport; };
export type PlanSummary = { "id": string; "status": "proposed" | "active" | "superseded" | "stale" | "rejected"; "validity": "feasible" | "invalid"; "optimization_run_id": string; "strategy": string; "base_input_revision": number; "base_state_version": number; "base_active_plan_id": (string | null); "config_version": number; "created_at": string; "cutover_sim_s": number; "forecast": Efficiency; "objective_value": (number | null); "changed_operation_ids": Array<string>; "explanation": Array<string>; "can_apply": boolean; };
export type PlannerLimits = { "time_limit_ms": number; "max_rollouts": number; };
export type RenderTelemetry = { "run_id": string; "event_seq": number; "client_id": string; "received_client_ms": number; "rendered_client_ms": number; "offset_ms": number; "uncertainty_ms": number; "visible": boolean; };
export type ReplanDetail = { "job": ReplanJob; "plans": Array<PlanDetail>; };
export type ReplanInput = { "request_id": string; "run_id": string; "expected_input_revision": number; "reason": "manual"; };
export type ReplanJob = { "id": string; "status": "queued" | "running" | "succeeded" | "no_feasible_plan" | "stale" | "timeout" | "failed"; "reason": string; "created_at": string; "started_at": (string | null); "finished_at": (string | null); "base_input_revision": number; "candidate_plan_ids": Array<string>; "applied_plan_id": (string | null); "elapsed_ms": number; "compute_ms": (number | null); "validation_ms": (number | null); "deadline_ms": 5000; "outcome_reason_codes": Array<string>; };
export type ReplanMetrics = { "elapsed": DurationStats; "compute": DurationStats; "succeeded": number; "no_feasible_plan": number; "stale": number; "timeout": number; "failed": number; "deadline_exceedances": number; };
export type Resource = { "id": string; "name": string; "kind": "shunting_locomotive" | "train_locomotive" | "self_propelled_unit" | "shunting_crew" | "inspection_crew" | "cargo_crew" | "train_crew"; "status": "available" | "busy" | "unavailable" | "unavailable_pending"; "active_operation_id": (string | null); "location": (PhysicalLocation | null); "available_after_sim_s": (number | null); "assigned_user_id": (string | null); };
export type RouteGeometry = { "id": string; "from_id": string; "to_id": string; "track_ids": Array<string>; "zone_ids": Array<string>; "points": Array<[number, number]>; };
export type ScenarioSummary = { "id": string; "name": string; "description": string; "train_count": number; "horizon_sim_s": number; "enabled_service_profiles": Array<"freight_transit_v1" | "freight_local_v1" | "freight_reclassify_v1" | "passenger_transit_v1" | "service_transit_v1">; };
export type ScenariosResponse = { "items": Array<ScenarioSummary>; };
export type SimulationCommand = { "request_id": string; "run_id": string; "expected_input_revision": number; "action": "play" | "pause" | "step" | "set_speed"; "speed"?: (1 | 5 | 10 | null); };
export type State = { "schema_version": "1.0"; "run_id": string; "scenario_id": string; "scenario_epoch": string; "event_seq": number; "state_version": number; "input_revision": number; "config_version": number; "server_time": string; "sim_time_s": number; "speed": 1 | 5 | 10; "mode": "paused" | "running"; "station": Station; "active_plan_id": (string | null); "tracks": Array<Track>; "zones": Array<Zone>; "trains": Array<Train>; "wagon_groups": Array<WagonGroup>; "resources": Array<Resource>; "operations": Array<Operation>; "incidents": Array<Incident>; "conflicts": Array<Conflict>; "plans": Array<PlanSummary>; "last_replan": (ReplanJob | null); "efficiency": Efficiency; };
export type Station = { "id": string; "name": string; "parks": Array<Park>; "layout": Layout; };
export type Track = { "id": string; "name": string; "park_id": string; "kind": "receiving_departure" | "lead" | "sorting" | "cargo" | "parking"; "length_m": number; "availability": "open" | "closed" | "closure_pending"; "occupied_length_m": number; "train_ids": Array<string>; "group_ids": Array<string>; "locomotive_ids": Array<string>; "assigned_train_id": (string | null); "active_operation_ids": Array<string>; };
export type TrackGeometry = { "track_id": string; "points": Array<[number, number]>; };
export type Train = { "id": string; "number": string; "type": "FREIGHT" | "PASSENGER" | "SERVICE" | "OTHER"; "service_profile_id": "freight_transit_v1" | "freight_local_v1" | "freight_reclassify_v1" | "passenger_transit_v1" | "service_transit_v1"; "processing_kind": "transit" | "local" | "reclassify"; "direction": "W_E" | "E_W"; "consist_kind": "wagon_groups" | "fixed"; "body_length_m": number; "total_length_m": number; "location": PhysicalLocation; "priority": 1 | 2 | 3; "status": "expected" | "waiting_entry" | "on_station" | "ready_departure" | "departed"; "destination_id": string; "scheduled_arrival_sim_s": number; "expected_arrival_sim_s": number; "due_departure_sim_s": number; "actual_arrival_sim_s": (number | null); "actual_departure_sim_s": (number | null); "group_ids": Array<string>; "target_group_ids"?: Array<string>; "traction_resource_id": string; "traction_kind": "locomotive" | "self_propelled"; "planned_track_id": (string | null); "current_track_id": (string | null); };
export type User = { "id": string; "display_name": string; "role": "viewer" | "operator" | "dispatcher" | "admin"; "resource_ids": Array<string>; };
export type ValidatorError = { "code": string; "entity_ids": Array<string>; "message": string; };
export type ValidatorReport = { "passed": boolean; "errors": Array<ValidatorError>; };
export type WagonGroup = { "id": string; "origin_train_id": string; "assigned_train_id": string; "current_train_id": (string | null); "wagon_ids": Array<string>; "wagon_count": number; "length_m": number; "destination_id": string; "cargo_state": "unloaded" | "loaded" | "not_applicable"; "location": PhysicalLocation; };
export type Zone = { "id": "W" | "E"; "active_operation_id": (string | null); "availability": "open" | "closed"; };

export interface StateCause { kind: string; entity_ids: string[]; ingested_at: string; }
export interface StateEvent { state: State; cause: StateCause; }
export interface ResetEvent { state: State; reason: string; }
export type SSEEventName = "state" | "reset";
